#github worflows build.yml
name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.1"
          architecture: "x64"
      - run: pip install uv
      - run: uv run isort main.py
      - run: uv run black main.py

      #- run: sphinx-build -b html source build
